# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mlApp.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 501, 81))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(110, 50, 151, 51))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(6, 132, 381, 301))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(436, 132, 361, 301))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 60, 141, 31))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 801, 551))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 90, 101, 31))
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 92, 91, 31))
        self.pushButton_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        self.menuImage_processing = QtWidgets.QMenu(self.menubar)
        self.menuImage_processing.setObjectName("menuImage_processing")
        self.menuText_classfication = QtWidgets.QMenu(self.menubar)
        self.menuText_classfication.setObjectName("menuText_classfication")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFace_detect = QtWidgets.QAction(MainWindow)
        self.actionFace_detect.setObjectName("actionFace_detect")
        self.actionFace_recognition = QtWidgets.QAction(MainWindow)
        self.actionFace_recognition.setObjectName("actionFace_recognition")
        self.actionDigits_recognition = QtWidgets.QAction(MainWindow)
        self.actionDigits_recognition.setObjectName("actionDigits_recognition")
        self.actionOther_objects_detection = QtWidgets.QAction(MainWindow)
        self.actionOther_objects_detection.setObjectName("actionOther_objects_detection")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionText_summarizer = QtWidgets.QAction(MainWindow)
        self.actionText_summarizer.setObjectName("actionText_summarizer")
        self.actionText_classification = QtWidgets.QAction(MainWindow)
        self.actionText_classification.setObjectName("actionText_classification")
        self.menuImage_processing.addAction(self.actionFace_detect)
        self.menuImage_processing.addAction(self.actionFace_recognition)
        self.menuImage_processing.addAction(self.actionDigits_recognition)
        self.menuImage_processing.addAction(self.actionOther_objects_detection)
        self.menuText_classfication.addAction(self.actionText_summarizer)
        self.menuText_classfication.addAction(self.actionText_classification)
        self.menuOptions.addAction(self.actionHome)
        self.menuOptions.addAction(self.actionExit)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuImage_processing.menuAction())
        self.menubar.addAction(self.menuText_classfication.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Machine Learning Applications"))
        self.pushButton.setText(_translate("MainWindow", "Choose Image"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Detect Faces"))
        self.pushButton_3.setText(_translate("MainWindow", "face store"))
        self.pushButton_4.setText(_translate("MainWindow", "face recognize"))
        self.menuImage_processing.setTitle(_translate("MainWindow", "image processing"))
        self.menuText_classfication.setTitle(_translate("MainWindow", "text processing"))
        self.menuOptions.setTitle(_translate("MainWindow", "options"))
        self.actionFace_detect.setText(_translate("MainWindow", "face detect"))
        self.actionFace_recognition.setText(_translate("MainWindow", "face recognition"))
        self.actionDigits_recognition.setText(_translate("MainWindow", "digits recognition"))
        self.actionOther_objects_detection.setText(_translate("MainWindow", "other objects detection"))
        self.actionHome.setText(_translate("MainWindow", "home"))
        self.actionExit.setText(_translate("MainWindow", "exit"))
        self.actionText_summarizer.setText(_translate("MainWindow", "text summarizer"))
        self.actionText_classification.setText(_translate("MainWindow", "text classification"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

